server:
  port: 8802

spring:
  application:
    name: eurekaServer

eureka:
  instance:
    hostname: eureka02
  # 开启之前需要修改一下客户端设置（虽然是服务端
  client:
    # 由于我们是作为服务端角色，所以不需要获取服务端，改为false，默认为true
    fetch-registry: false
    # 将eureka服务端指向其他服务
    service-url:
      defaultZone: http://eureka01:8801/eureka